name:         uniform-fileio
version:      0.1.3
license:      GPL-2.0-only
# license-file: GPL_3
maintainer:   Andrew U. Frank <uniform@gerastree.at>
bug-reports:  https://github.com/andrewufrank/uniform-fileio/issues
author:       Andrew Frank
copyright:    2021 Andrew U. Frank
category:     Data Text Uniform
synopsis: Uniform file handling operations
description: |
  Uniform operations for handling files and file path names
  independent from the representation. 

  Additionally, functions to read and write files for specific 
  typed content (marked by extension).

  added stack build lts 19.16 for ghc 9.0.2
  
  Please see the README on GitHub at <https://github.com/andrewufrank/uniform-fileiio/readme>

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- monads-tf
- safe
- text
- bytestring
- directory
- pureMD5
- deepseq
- unix
- pipes
- path
- path-io
- filepath
- exceptions
- zlib
- uniform-strings  >= 0.1.3
- uniform-error    >= 0.1.4
- uniform-algebras >= 0.1.4
- uniform-time     >= 0.1.0

library:
  source-dirs: 
    - .
  verbatim:
    autogen-modules:
        Paths_uniform_fileio

# this is only a library, no directly executable
# executables:
#   primo-exe:
#     main:                Testing.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - uniform-algebras

tests:
  fileio-test:
    main:                Testing.hs
    source-dirs:         tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HTF
    - test-invariant
    - quickcheck-text
    - uniform-fileio
